### ISSUE TITLE
angular 2 router

### ISSUE THREAD

**Issue by kweheliye** [timjacobi/angular2-education#10]
Easy place find all the latest news, updates  and article related to Angular 2.

I'll be checking this repository in every now then. do you have any angular 2 router article or example ?  do you have any idea when the angular 2 router will be available ? thanks

**Comment by timjacobi** [comment]
Unfortunately there is no information yet as to what the syntax for the new router will be. Not even in Googles design documents.

**Comment by ShMcK** [comment]
The [router codebase](https://github.com/angular/router) has some examples written in Angular 1. But notice the build is currently failing, likely under some serious changes.

**Comment by timjacobi** [comment]
Yeah there are A1 examples all over the place but I didn't mention them as @kweheliye specifically asked for A2 examples.
