### ISSUE TITLE
More Angular2 Links

### ISSUE THREAD

**Issue by orizens** [timjacobi/angular2-education#111]
### Articles 
[Integrating Ngrx and Angular2](http://orizens.com/wp/topics/adding-redux-with-ngrxstore-to-angular-2-part-1/) 
[From Angular 1.x ng-repeat to Angular 2 NgFor with Component](http://orizens.com/wp/topics/from-angular-1-x-ng-repeat-to-angular-2-ngfor-with-component/)
[Migrating A Component From Angular 1.x to Angular 2](http://orizens.com/wp/topics/migrating-a-component-to-angular-2-from-angular-1-x-es2015/) 
[Angular 2: Attribute @Directive() & Creating An Infinite Scroll Directive](http://orizens.com/wp/topics/angular-2-attribute-directive-creating-an-infinite-scroll-directive/) 
### Example
[Echoes Player open source app in ng2](http://github.com/orizens/echoes-ng2) 

### Directive 
[Angular2 Infinite Scroll Directive](https://www.npmjs.com/package/angular2-infinite-scroll)

**Comment by timjacobi** [comment]
Thanks. Would you mind sending a PR?
