### ISSUE TITLE
Add Awesome Angular 2 Components Catalog

### ISSUE THREAD

**Issue by Chyngyz** [timjacobi/angular2-education#172]
Hi,

Thanks for great educational resource list.
I've created the [Awesome Angular 2 Components Catalog](https://github.com/Chyngyz/awesome-angular2-components) and look forward to actively update and support it. 
You can add link to the catalog in your **Components**  block.
Hope it will be of good use and help.

Thanks.

**Comment by timjacobi** [comment]
Added, thank you! :)
