### ISSUE TITLE
Infowrap as an additional option alongside the repo to ease curating the list

### ISSUE THREAD

**Issue by NathanWalker** [timjacobi/angular2-education#29]
@timjacobi Thanks for an excellent resource on Angular 2!

I wrapped all the info from the README here: https://infowrap.com/angular2
Infowrap is an AngularJS 1.x app itself and is in the process of being converted to Angular 2.
It allows for other things that might be nice to have separated out for a curated educational resource like this.
Others can join to collaborate on all the information with this link:
https://infowrap.com/angular2?collaborate=d6e035d6-f996-4888-9b9f-32cf8442bf2b

Or they can simply follow the wrap to receive updates to any changes here:
https://infowrap.com/angular2?follow=true

Let me know if you might find this useful as it may allow more people to easily add useful information  without the need to process through pull requests.

**Comment by timjacobi** [comment]
Yeah that sounds, really good. Thanks for the heads up.
