### ISSUE TITLE
Angula 2 Localization

### ISSUE THREAD

**Issue by robisim74** [timjacobi/angular2-education#54]
Hi @timjacobi,

I've created an experimental app to simply implement the translation in Angular 2, through a injectable class. You can find it [here](https://github.com/robisim74/angular2localization.git).
I think it can be interesting for others because it shows the potential of hierarchical dependency injection.
If you like it, may you add it to your list?

Thanks!

**Comment by timjacobi** [comment]
Hi Rob,

thanks for the link. Do you think you could add some more explanations so people can benefit more from the app?

**Comment by robisim74** [comment]
Yes, I'm going to do it. I will update you as soon as ready.

**Comment by robisim74** [comment]
Hi Tim,

I've added some more explanations about the application working: I hope they can be helpful.
Thank you for your tip.

Bye!

**Comment by timjacobi** [comment]
Sorry for the delay! It looks good. Would you mind sending a PR and I'll merge it in? Thanks!
