### ISSUE TITLE
Add ng2Challenges

### ISSUE THREAD

**Issue by ShMcK** [timjacobi/angular2-education#7]
https://github.com/ShMcK/ng2Challenges

Perhaps add to tutorials or example apps? Not too sure where it fits.

**Comment by crissdev** [comment]
@ShMcK How does that repo helps in _getting started_ with Angular 2?

--
angular2-education
> A curated list of helpful material to get started with education on Angular 2

**Comment by ShMcK** [comment]
You have a point. It currently may not be good for 'getting started', it's aimed more at high-beginners with a functional understanding of Angular2. 

As well,  it's not really there yet. The mini-projects should really be scaffolded more with better comments and explanations. However, if people post solutions, I think it could be a good resource for all kinds of angular2 learners. I've found reading other peoples code to be most helpful. I'll post my own solutions at some point.

I agree, a curated list should be curated. I'll leave it up to your discretion.

**Comment by crissdev** [comment]
@ShMcK Just in case you didn't notice a [link](https://github.com/timjacobi/angular2-education/blob/master/README.md#example-apps) was included in the README.md.

The idea of the repo is great but additional text in the Wiki, for instance, would be helpful. :+1:

**Comment by ShMcK** [comment]
Thanks! I'll try to make the explanation clearer.

**Comment by kweheliye** [comment]
Good stuff @ShMcK , you already have small mini login implementation of  the control and form. excellent.

**Comment by ShMcK** [comment]
@kweheliye Working on a presentation for this weekend, check it out so far: http://tryangular2.github.io. I'll try to add a form validation example.

**Comment by kweheliye** [comment]
@ShMcK  Good luck with your presentation, if you recording  please share it..
