### ISSUE TITLE
Please add this to repo

### ISSUE THREAD

**Issue by born2net** [timjacobi/angular2-education#79]
Thanks for a great repo... I just posted a massive Angular 2 bootstrap project. Anyone interested om Angular 2 will love it. Check out the working demo @ http://ng2.javascriptninja.io and source at: https://github.com/born2net/ng2Boilerplate

regards

Sean.

**Comment by crissdev** [comment]
@born2net Nice one!
:+1:

**Comment by timjacobi** [comment]
Thanks! Would you mind sending a PR?
