### ISSUE TITLE
Intro to Angular 2 (David East) Doesn't display anything except for the angular 2 logo

### ISSUE THREAD

**Issue by Gnarlywhale** [timjacobi/angular2-education#92]
When [the link](Intro to Angular 2 (David East)) loads, all that is displayed is the logo and "Introduction to Angular 2." Nothing else loads and there doesn't appear to be a way to navigate around. Not sure if this is just a problem on my end or if something is up with the firebase app (can still see the content in the page source). 
![image](https://cloud.githubusercontent.com/assets/3422267/12300375/66268948-b9d8-11e5-99ce-0fe202c93d9c.png)

Resource should be updated or removed from the list.

**Comment by FrancescoMussi** [comment]
On my side it looks the same.
Intro to Angular 2 (David East) contains nothing but a logo.

https://angular2-intro.firebaseapp.com/#/

**Comment by Gnarlywhale** [comment]
You navigate the deck using arrow keys, have you tried doing that?

**Comment by FrancescoMussi** [comment]
Oh i see.. Well then the user should be advised about it with a simple line instruction, since is not usual navigation.
Otherwise he will never know about it.
